Execution of processAllLogs_new.py started at 2020-07-09 05:00:02.205770
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-08/13
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-08/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-08/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-08/16
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-08/17
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-08/18
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-08/19
making directory: /h
Execution of processAllLogs_new.py started at 2020-07-10 05:00:03.757422
Now processing logs0
making directory: /h
Execution of processAllLogs_new.py started at 2020-07-11 05:00:03.291421
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-10/13
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-10/17
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-10/19
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-10/20
making directory: /h
Execution of processAllLogs_new.py started at 2020-07-12 05:00:02.045998
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-11/12
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-11/13
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-11/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-11/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-11/16
Execution of processAllLogs_new.py started at 2020-07-13 05:00:02.441420
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-12/20
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-11/11
Execution of processAllLogs_new.py started at 2020-07-14 05:00:01.664945
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-13/20
Execution of processAllLogs_new.py started at 2020-07-14 16:01:02.339468
Now processing logs0
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/12
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/13
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/15
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-14/15
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 16:39:57.772643
Execution of processAllLogs_new.py started at 2020-07-14 17:01:01.978103
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/16
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Now processing logs1
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-14/16
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 17:08:00.852286
Execution of processAllLogs_new.py started at 2020-07-14 18:01:01.937295
Now processing logs0
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/17
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-14/17
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 18:12:31.494840
Execution of processAllLogs_new.py started at 2020-07-14 19:01:01.663457
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/18
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Now processing logs1
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-14/18
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 19:09:31.431805
Execution of processAllLogs_new.py started at 2020-07-14 20:01:01.531518
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Now processing logs1
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 20:08:03.923849
Execution of processAllLogs_new.py started at 2020-07-14 21:01:01.728527
Now processing logs0
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-14/20
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-14/20
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 21:10:04.199276
Execution of processAllLogs_new.py started at 2020-07-14 22:01:01.706854
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 22:08:22.673420
Execution of processAllLogs_new.py started at 2020-07-14 23:01:02.449362
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-14 23:08:22.584078
Execution of processAllLogs_new.py started at 2020-07-15 00:01:02.074588
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 00:08:46.931714
Execution of processAllLogs_new.py started at 2020-07-15 01:01:01.957803
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 01:14:47.677055
Execution of processAllLogs_new.py started at 2020-07-15 02:01:01.881450
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 02:14:57.915978
Execution of processAllLogs_new.py started at 2020-07-15 03:01:02.330280
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 03:15:02.927684
Execution of processAllLogs_new.py started at 2020-07-15 04:01:02.019703
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 04:14:38.039635
Execution of processAllLogs_new.py started at 2020-07-15 05:01:01.849622
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 05:14:32.647740
Execution of processAllLogs_new.py started at 2020-07-15 06:01:02.042753
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 06:15:18.855002
Execution of processAllLogs_new.py started at 2020-07-15 07:01:01.856551
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 07:14:47.468506
Execution of processAllLogs_new.py started at 2020-07-15 08:01:02.057975
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-15/07
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-15/07
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 08:18:54.573715
Execution of processAllLogs_new.py started at 2020-07-15 09:01:02.177080
Now processing logs0
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:50:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_17:00:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:45:04_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_17:55:04_0.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:30:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-14_11:35:03_0.log
Could not process file: /home/ardelalegre/google-drive/ODAS/logs0/SST/cSST_2020-07-09_16:55:04_0.log
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-14_16:50:04_1.log
making directory: /h
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-15 09:15:03.860870
Execution of processAllLogs_new.py started at 2020-07-15 11:01:02.393984
Now processing logs0
Execution of processAllLogs_new.py started at 2020-07-15 12:01:01.520058
Now processing logs0
Execution of processAllLogs_new.py started at 2020-07-15 13:01:02.317255
Now processing logs0
making directory: /h
Execution of processAllLogs_new.py started at 2020-07-15 14:01:02.327757
Now processing logs0
Execution of processAllLogs_new.py started at 2020-07-15 15:01:02.142577
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-14_21:55:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 16:01:02.111438
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-14_21:55:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 17:01:01.597728
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-08_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 18:01:02.466763
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 19:01:02.349883
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 20:01:02.261838
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 21:01:01.728535
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 22:01:01.838215
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-15 23:01:02.098389
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 00:01:01.760015
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 01:01:01.617874
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 02:01:02.248267
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 03:01:02.033556
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 04:01:02.388727
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 05:01:01.532100
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 06:01:01.687614
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 07:01:02.295131
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-12_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 08:01:01.719988
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 105, in <module>
    firstline = f.readline()
IOError: [Errno 5] Input/output error
Execution of processAllLogs_new.py started at 2020-07-16 09:01:01.634932
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 105, in <module>
    firstline = f.readline()
IOError: [Errno 5] Input/output error
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-16 10:01:01.765451
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-15/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-15/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-15/16
making directory: /h
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-08_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 11:01:01.476227
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-10_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 12:01:01.997755
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-10_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 13:01:01.638961
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-10_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 14:01:02.413279
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-10_04:45:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 15:01:01.740056
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-14_18:55:04_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 16:01:02.816723
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-14_22:55:03_0.log' already exists
Execution of processAllLogs_new.py started at 2020-07-16 17:01:02.153825
Now processing logs0
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 107, in <module>
    temp = shutil.move(log,destination) # new
  File "/usr/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
shutil.Error: Destination path '/home/ardelalegre/google-drive/ODAS/logs0/SST/Processed/cSST_2020-07-15_06:50:03_0.log' already exists
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-16 19:01:01.600591
Now processing logs0
making directory: /h
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-16/18
Now processing logs1
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/18
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 104, in <module>
    with open(log, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-15_14:15:04_1.log'
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-16 20:01:02.358004
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 104, in <module>
    with open(log, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-16_16:00:04_1.log'
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-16 21:01:02.523336
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 104, in <module>
    with open(log, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-07-16_07:30:03_1.log'
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-16 22:01:01.581287
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/18
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 104, in <module>
    with open(log, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/ardelalegre/google-drive/ODAS/logs2/SST/cSST_2020-07-16_17:10:04_2.log'
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-16 18:01:02.376926
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-16/16
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-16/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-16/17
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-16/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-16/13
making directory: /h
Now processing logs1
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/13
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-15/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-15/16
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-15/14
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/11
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/00
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/17
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-16/16
making directory: /h
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-15/17
Now processing logs2
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-15/15
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-15/16
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/16
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-15/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/14
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/13
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/17
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/05
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-15/17
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-16/11
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-16 23:21:39.056289


Execution of processAllLogs_new.py started at 2020-07-16 23:01:01.670441
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Traceback (most recent call last):
  File "/home/ardelalegre/CSE4223-ODAS/preprocessing/python/processAllLogs_new.py", line 104, in <module>
    with open(log, 'r') as f:
IOError: [Errno 2] No such file or directory: '/home/ardelalegre/google-drive/ODAS/logs2/SST/cSST_2020-07-15_16:05:05_2.log'
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 00:01:01.642447
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 00:14:00.592023


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 01:01:02.288439
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 01:13:35.680951


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 02:01:02.421884
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 02:13:29.017165


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 03:01:01.655828
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 03:13:33.083224


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 04:01:01.746796
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 04:13:26.364996


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 05:01:02.123989
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 05:13:34.709282


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 06:01:02.408680
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 06:22:13.660060


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 07:01:02.351126
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 07:19:13.373686


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 08:01:02.140224
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-17/07
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 08:28:32.545831


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 09:01:02.195456
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 09:27:01.580611


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 10:01:02.320494
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
Now processing logs2
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 10:13:59.033705


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 11:01:01.790789
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-17/10
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-17/10
making directory: /h
Now processing logs2
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-17/10
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 11:14:17.988871


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 12:01:01.723657
Now processing logs0
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-17/11
making directory: /h
Now processing logs2
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-17/11
Now processing logs3
Execution of processAllLogs_new.py ended at 2020-07-17 12:16:27.750095


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
Execution of processAllLogs_new.py started at 2020-07-17 13:01:02.418068
Now processing logs0
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes0/2020-07-17/12
making directory: /h
Now processing logs1
Could not process file: /home/ardelalegre/google-drive/ODAS/logs1/SST/cSST_2020-06-26_13:00:12_1.log
making directory: /h
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes1/2020-07-17/12
Now processing logs2
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes2/2020-07-17/12
Now processing logs3
making directory: /home/ardelalegre/google-drive/ODAS/dataframes/dataframes3/2020-07-17/12
Execution of processAllLogs_new.py ended at 2020-07-17 13:58:44.682137


/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)
